### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by sorrycc** [dvajs/dva#6]
想到和收集到的需求整理如下：

- Framework
  - [x] 完成整体设计 (包含 api，addon/plugin/hook, 赋能和约束的权衡, config, 性能, model 和 routes 的动态加载 等等)
  - [x] HMR 支持: components and routes
  - [x] npm publish 前做 umd 构建
  - [x] Test Case
  - [x] 1-2 个 addon，比如 loading 状态的自动添加
- Docs
  - [x] Quick Start
  - [x] Tutorial (一个完整的教程，通过一步步引导熟悉 dva 的所有概念)
  - [x] Concepts
  - [x] API
  - [x] dva 课程开发 (面向内部全栈同学)
- Tools
  - [x] dva-cli (init, generate, 考虑封装 ant-tool 及其配置)
  - [x] dva-ast

如有遗漏，请在下面评论添加。1.0 尽量把所有 api 都敲定，难免会有一些 break change 。

**Comment by Tinker404** [comment]
目前写了写感觉非常棒, 期待文档, router的history的API配置有考虑进去吗?

**Comment by sorrycc** [comment]
history 现在就可配的，[ref](https://github.com/sorrycc/dva/blob/2bb8bf95a87476385541fcd6f54024edfaac8b20/src/index.js#L51)。如果要换成 browserHistory，可以这么做：

```javascript
import dva from 'dva';
import { browserHistory } from 'dva/router';

const app = dva();
// 在 start 时传入 history
app.start(container, {
  history: browserHistory,
});
```

**Comment by Tinker404** [comment]
这个设置browserHistory的确好用了,之前我是hashHistory并设置{queryKey: false}来去除随机生成的hash的,但是现在用DVA还是会有随机生成的hash,不知道有没有考虑过这类需求?

**Comment by sorrycc** [comment]
@Tinker404 https://github.com/reactjs/react-router/blob/e75a70866fa738f8b2aa7db8a1cdc5f846dbfc0a/upgrade-guides/v2.0.0.md#using-custom-histories

**Comment by Tinker404** [comment]
抱歉,可能我没表达清楚,我是按照router文档2.0的设置的,history的版本是2.0
`const appHistory = useRouterHistory(createHashHistory)({ queryKey: false })
  app.start(container, {
  history: appHistory,
});`

这样设置后还是有hash

**Comment by sorrycc** [comment]
https://github.com/sorrycc/dva/commit/4bb6ab709334d59f1133572c146db9ce1bb998cf
试过可以的。

**Comment by Tinker404** [comment]
查了一下发现是用了hashHistory这个API的关系,去掉就解决了,不知道有没有别的API能代替
```javascript
subscriptions: [
    function (dispatch) {
      hashHistory.listen(location => {
        if (location.pathname === '/tabs') {
          dispatch({type: 'FETCH_DATA'});
        }
      });
    }
  ]

**Comment by popomore** [comment]
model 是否可以改成面向对象的写法，也便于扩展，

```js
// 字面量
const model = new app.Model({
  namespace,
  state,
  ..  
});

// 方法
const model = new app.Model()
.namespace('')
.state({});

// 也方便扩展
class CustomModel extends app.Model {};
```

views 层是否也可以管理起来，现在还需要手动写 connect，其实这一步可以默认做掉，没有任何 map 也不影响

```js
class ConnectComponent extends react.Component {}

class MyComponent extends ConnectComponent {
  
  mapStateToProps(state) {
    return {
      prop: state.prop,
    }
  }
}
```

**Comment by sorrycc** [comment]
项目做下来，感觉用到继承的点并不多，真要扩展，推荐通过 high order function  的方式做。View 也是一样，React 社区也是倾向于用 pure function 的 component 形式。

connect 有考虑封装，和 reselect 结合，默认加缓存，保持高性能。但一个类似 mapStateToProps 的方法应该是没法省的。

**Comment by popomore** [comment]
mapStateToProps 是没法省的。

业务实践可以，但社区方案应该更加可扩展。

**Comment by codering** [comment]
问下工程目录结构大致怎样的？以后的cli工具也应该遵循一定规范的吧。
看了https://github.com/sorrycc/dva/tree/master/examples/user-dashboard/src， 会按照这个结构来吗?

**Comment by sorrycc** [comment]
@codering 是的，基本上就按这个目录了。

**Comment by fengmk2** [comment]
dva 我建议不要放个人项目来做。

**Comment by sorrycc** [comment]
@fengmk2 我建个 group 。

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva

**Comment by LeuisKen** [comment]
自己写了一个demo，对参与`Quick Start`和`Tutorial`的编写很有兴趣。

**Comment by gzhappysky** [comment]
能有一些线上的案例介绍吗

**Comment by sorrycc** [comment]
@gzhappysky 为什么要 **线上** 的案例介绍? 你想了解哪方面的内容，最好详细点。

**Comment by gzhappysky** [comment]
@sorrycc 我想看一下用saga或者dva写出来的系统体验如何，学习一下！

**Comment by WhatAKitty** [comment]
@sorrycc npmjs上有1.0的beta吗?发现0.16和1.0-beta的版本中subscriptions的类型不一致。

**Comment by sorrycc** [comment]
@WhatAKitty 参考这份文档升级，1.0-beta 里一些 break change 。

**Comment by itiwll** [comment]
1.0  , HMR 支持了吗？ 要怎么配置？

**Comment by sorrycc** [comment]
@itiwll 支持 components 和 routes 的，基于 babel 插件实现，指定 entry 文件。例子：https://github.com/dvajs/dva-cli/blob/master/boilerplates/app/webpack.config.js#L7-L14

**Comment by itiwll** [comment]
@sorrycc 可是用 `dva-cli 4.0` init 的新项目我不管改那个文件都会刷新页面。

**Comment by itiwll** [comment]
@sorrycc 可是我不管修改什么文件都会刷新页面

**Comment by itiwll** [comment]
`xxx.hot-update.json`和`xxx.hot-update.js`返回的数据始终是空的。

**Comment by itiwll** [comment]
刚刚尝试在ubuntu下`dva-cli@0.4.0` init 的新项目 HRM 是可以的，windows 下要做什么才可以？

**Comment by sorrycc** [comment]
抱歉，没有 windows 环境，定位不了问题。 hmr 是辅助功能，windows 就关闭此功能吧。。

**Comment by itiwll** [comment]
```
[HMR] connected
client.js:127 [HMR] bundle rebuilding
client.js:130 [HMR] bundle rebuilt in 320ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:81[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
process-update.js:89[HMR]  - ./src/routes/IndexPage.jsx
process-update.js:128[HMR] Reloading page
Navigated to http://localhost:8989/
```

**Comment by sorrycc** [comment]
@itiwll windows 下我帮不上忙，可能是 hmr 本身就不支持 windows ?

**Comment by hbrls** [comment]
dva 课程开发 (面向内部全栈同学)

这个能放一部分出来吗？
